@startuml
:Компудахтер: --> (Получить изображение с камеры)
:Компудахтер: --> (Искать на изображении граффити)
:Компудахтер: --> (Определить координаты граффити)
:Компудахтер: --> (Переслать данные роботу о положении графити)
:Компудахтер: --> (Искать на изображении робота)
@enduml